document.addEventListener('DOMContentLoaded',()=>{
'use strict';
const $=id=>document.getElementById(id), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const api=async(url,opt={})=>{const r=await fetch(url,{credentials:'same-origin',...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d};
const LANGS=[
 ['en','English','ltr'],['zh','中文','ltr'],['ur','اردو','rtl'],['ps','پښتو','rtl'],['fa','فارسی / دری','rtl'],['ru','Русский','ltr'],['id','Bahasa Indonesia','ltr'],['ms','Bahasa Melayu','ltr'],['ar','العربية','rtl'],['tr','Türkçe','ltr']
];
const UI={
 en:{home:'Home',trade:'Trade & Business',research:'Research & Knowledge',admin:'Admin',language:'Language',explore:'Explore',back:'Back',ai:'Royal AI Assistant',gallery:'Project Gallery',contact:'WhatsApp',addresses:'Offices & Contact',manage:'Manage',login:'Login',logout:'Logout',create:'Create Folder',save:'Save',delete:'Delete',edit:'Edit',name:'Name',description:'Description',section:'Section',folder:'Folder',visible:'Visible',hidden:'Hidden',welcome:'Royal Chilghoza Pine Nuts',tagline:'Pakistan • Origin • Global',
 premium:'Premium Chilghoza Pine Nuts',tradeLead:'Origin, quality, supply and global business information for buyers and partners.',researchLead:'Origin, harvesting, science, GI, forests and knowledge for a permanent research home.'},
 zh:{home:'首页',trade:'贸易与商业',research:'研究与知识',admin:'管理',language:'语言',explore:'探索',back:'返回',ai:'Royal AI 助手',gallery:'项目图库',contact:'WhatsApp',addresses:'办公室与联系',manage:'管理',login:'登录',logout:'退出',create:'创建文件夹',save:'保存',delete:'删除',edit:'编辑',name:'名称',description:'描述',section:'栏目',folder:'文件夹',visible:'显示',hidden:'隐藏',welcome:'Royal Chilghoza Pine Nuts',tagline:'巴基斯坦 • 原产地 • 全球',premium:'优质松子',tradeLead:'面向全球买家的产地、品质、供应和商业信息。',researchLead:'产地、采收、科学、GI、森林与知识研究。'},
 ur:{home:'ہوم',trade:'تجارت و کاروبار',research:'تحقیق و علم',admin:'ایڈمن',language:'زبان',explore:'ملاحظہ',back:'واپس',ai:'Royal AI معاون',gallery:'پروجیکٹ گیلری',contact:'واٹس ایپ',addresses:'دفاتر و رابطہ',manage:'انتظام',login:'لاگ اِن',logout:'لاگ آؤٹ',create:'فولڈر بنائیں',save:'محفوظ',delete:'حذف',edit:'ترمیم',name:'نام',description:'تفصیل',section:'سیکشن',folder:'فولڈر',visible:'نمایاں',hidden:'مخفی',welcome:'Royal Chilghoza Pine Nuts',tagline:'پاکستان • اصل • عالمی',premium:'اعلیٰ معیار چلغوزہ',tradeLead:'عالمی خریداروں کے لیے اصل، معیار، سپلائی اور کاروباری معلومات۔',researchLead:'اصل، برداشت، سائنس، GI، جنگلات اور تحقیقی معلومات۔'},
 ps:{home:'کور',trade:'سوداګري او تجارت',research:'څېړنه او پوهه',admin:'اداره',language:'ژبه',explore:'کتنه',back:'شاته',ai:'Royal AI مرستیال',gallery:'انځورونو ټولګه',contact:'واټس اپ',addresses:'دفترونه او اړیکه',manage:'مدیریت',login:'ننوتل',logout:'وتل',create:'فولډر جوړول',save:'خوندي کول',delete:'ړنګول',edit:'سمون',name:'نوم',description:'تشریح',section:'برخه',folder:'فولډر',visible:'ښکاره',hidden:'پټ',welcome:'Royal Chilghoza Pine Nuts',tagline:'پاکستان • اصلي • نړیوال',premium:'لوړ کیفیت چلغوزه',tradeLead:'د نړیوالو پېرودونکو لپاره د اصل، کیفیت، عرضې او سوداګرۍ معلومات.',researchLead:'اصل، ټولونه، ساینس، GI، ځنګلونه او څېړنه.'},
 fa:{home:'خانه',trade:'تجارت و کسب‌وکار',research:'پژوهش و دانش',admin:'مدیریت',language:'زبان',explore:'مشاهده',back:'بازگشت',ai:'دستیار Royal AI',gallery:'گالری پروژه',contact:'واتساپ',addresses:'دفاتر و تماس',manage:'مدیریت',login:'ورود',logout:'خروج',create:'ایجاد پوشه',save:'ذخیره',delete:'حذف',edit:'ویرایش',name:'نام',description:'توضیحات',section:'بخش',folder:'پوشه',visible:'نمایش',hidden:'پنهان',welcome:'Royal Chilghoza Pine Nuts',tagline:'پاکستان • خاستگاه • جهانی',premium:'چلغوزای ممتاز',tradeLead:'اطلاعات مبدأ، کیفیت، عرضه و تجارت جهانی برای خریداران.',researchLead:'مبدأ، برداشت، علم، GI، جنگل‌ها و پژوهش.'},
 ru:{home:'Главная',trade:'Торговля и бизнес',research:'Исследования и знания',admin:'Админ',language:'Язык',explore:'Открыть',back:'Назад',ai:'Royal AI',gallery:'Галерея',contact:'WhatsApp',addresses:'Офисы и контакты',manage:'Управление',login:'Войти',logout:'Выйти',create:'Создать папку',save:'Сохранить',delete:'Удалить',edit:'Изменить',name:'Название',description:'Описание',section:'Раздел',folder:'Папка',visible:'Видимо',hidden:'Скрыто',welcome:'Royal Chilghoza Pine Nuts',tagline:'Пакистан • Происхождение • Мир',premium:'Премиальный чилгоза',tradeLead:'Происхождение, качество, поставки и международная торговля.',researchLead:'Происхождение, сбор, наука, GI, леса и исследования.'},
 id:{home:'Beranda',trade:'Perdagangan & Bisnis',research:'Riset & Pengetahuan',admin:'Admin',language:'Bahasa',explore:'Jelajahi',back:'Kembali',ai:'Asisten Royal AI',gallery:'Galeri Proyek',contact:'WhatsApp',addresses:'Kantor & Kontak',manage:'Kelola',login:'Masuk',logout:'Keluar',create:'Buat Folder',save:'Simpan',delete:'Hapus',edit:'Edit',name:'Nama',description:'Deskripsi',section:'Bagian',folder:'Folder',visible:'Terlihat',hidden:'Tersembunyi',welcome:'Royal Chilghoza Pine Nuts',tagline:'Pakistan • Asal • Global',premium:'Chilghoza Premium',tradeLead:'Asal, kualitas, pasokan dan informasi bisnis global.',researchLead:'Asal, panen, sains, GI, hutan dan penelitian.'},
 ms:{home:'Utama',trade:'Perdagangan & Perniagaan',research:'Penyelidikan & Pengetahuan',admin:'Admin',language:'Bahasa',explore:'Teroka',back:'Kembali',ai:'Pembantu Royal AI',gallery:'Galeri Projek',contact:'WhatsApp',addresses:'Pejabat & Hubungan',manage:'Urus',login:'Log masuk',logout:'Log keluar',create:'Cipta Folder',save:'Simpan',delete:'Padam',edit:'Edit',name:'Nama',description:'Penerangan',section:'Bahagian',folder:'Folder',visible:'Kelihatan',hidden:'Tersembunyi',welcome:'Royal Chilghoza Pine Nuts',tagline:'Pakistan • Asal • Global',premium:'Chilghoza Premium',tradeLead:'Asal, kualiti, bekalan dan maklumat perniagaan global.',researchLead:'Asal, tuaian, sains, GI, hutan dan penyelidikan.'},
 ar:{home:'الرئيسية',trade:'التجارة والأعمال',research:'البحث والمعرفة',admin:'الإدارة',language:'اللغة',explore:'استكشف',back:'رجوع',ai:'مساعد Royal AI',gallery:'معرض المشروع',contact:'واتساب',addresses:'المكاتب والتواصل',manage:'إدارة',login:'دخول',logout:'خروج',create:'إنشاء مجلد',save:'حفظ',delete:'حذف',edit:'تعديل',name:'الاسم',description:'الوصف',section:'القسم',folder:'المجلد',visible:'ظاهر',hidden:'مخفي',welcome:'Royal Chilghoza Pine Nuts',tagline:'باكستان • الأصل • عالمي',premium:'تشلغوزا فاخر',tradeLead:'المصدر والجودة والتوريد ومعلومات التجارة العالمية.',researchLead:'المصدر والحصاد والعلوم وGI والغابات والبحث.'},
 tr:{home:'Ana Sayfa',trade:'Ticaret ve İş',research:'Araştırma ve Bilgi',admin:'Yönetim',language:'Dil',explore:'Keşfet',back:'Geri',ai:'Royal AI Asistanı',gallery:'Proje Galerisi',contact:'WhatsApp',addresses:'Ofisler ve İletişim',manage:'Yönet',login:'Giriş',logout:'Çıkış',create:'Klasör Oluştur',save:'Kaydet',delete:'Sil',edit:'Düzenle',name:'Ad',description:'Açıklama',section:'Bölüm',folder:'Klasör',visible:'Görünür',hidden:'Gizli',welcome:'Royal Chilghoza Pine Nuts',tagline:'Pakistan • Menşei • Küresel',premium:'Premium Chilghoza',tradeLead:'Menşei, kalite, tedarik ve küresel ticaret bilgileri.',researchLead:'Menşei, hasat, bilim, GI, ormanlar ve araştırma.'}
};
let lang=localStorage.getItem('rcpn_language')||'en', admin=false, folders={trade:[],research:[]};
const t=k=>(UI[lang]&&UI[lang][k])||UI.en[k]||k;
function applyLanguage(){const meta=LANGS.find(x=>x[0]===lang)||LANGS[0];document.documentElement.lang=meta[0];document.documentElement.dir=meta[2];$$('[data-i18n]').forEach(e=>e.textContent=t(e.dataset.i18n));const b=$('#languageButton');if(b)b.textContent=meta[1]+' ▾';renderFolders('trade');renderFolders('research');}
function languageMenu(){const m=$('#languageMenu');if(!m)return;m.innerHTML=LANGS.map(x=>`<button type="button" class="lang-option" data-lang="${x[0]}">${x[1]}</button>`).join('');$$('.lang-option',m).forEach(b=>b.onclick=()=>{lang=b.dataset.lang;localStorage.setItem('rcpn_language',lang);m.hidden=true;applyLanguage()});}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const img=['01-chilghoza-lot.jpg','02-chilghoza-cones.jpg','03-chilghoza-kernel.jpg','04-chilghoza-harvest.jpg','05-chilghoza-raw-kernels.jpg','06-chilghoza-cone-closeup.jpg','07-chilghoza-products-display.jpg','08-chilghoza-forest.jpg'];
async function loadHome(){const g=$('#homeGallery');if(!g)return;try{const d=await api('/api/home-images');const a=(d.images||d.media||[]).filter(x=>x.url).slice(0,8);g.innerHTML=(a.length?a:img.map((url,i)=>({url,title:`Chilghoza ${i+1}`}))).map(x=>`<figure><img loading="lazy" src="${esc(x.url)}" alt="${esc(x.alt||x.title||'Royal Chilghoza')}"><figcaption>${esc(x.title||'Royal Chilghoza')}</figcaption></figure>`).join('')}catch{g.innerHTML=img.map((url,i)=>`<figure><img loading="lazy" src="/${url}" alt="Royal Chilghoza ${i+1}"><figcaption>Royal Chilghoza</figcaption></figure>`).join('')}}
async function loadFolders(){for(const sec of ['trade','research']){try{const d=await api(`/api/folders?section=${sec}`);folders[sec]=Array.isArray(d)?d:(d.folders||[])}catch{folders[sec]=[]}renderFolders(sec)}}
function renderFolders(sec){const box=$(sec==='trade'?'tradeFolders':'researchFolders');if(!box)return;const list=folders[sec]||[];box.innerHTML=list.map((x,i)=>`<article class="folder-card" tabindex="0" data-folder="${esc(x.id||'')}" data-section="${sec}"><div class="folder-image"><img src="/${img[i%img.length]}" alt=""></div><div class="folder-body"><span class="folder-kicker">${sec==='trade'?'GLOBAL TRADE':'RESEARCH • KNOWLEDGE'}</span><h3>${esc(x.name||x.title||'Untitled')}</h3><p>${esc(x.description||x.desc||'')}</p><span class="folder-open">${t('explore')} ↗</span></div></article>`).join('')||`<div class="empty-state">${sec==='trade'?t('tradeLead'):t('researchLead')}</div>`;$$('.folder-card',box).forEach(c=>c.onclick=()=>openFolder(c.dataset.section,c.dataset.folder));}
async function openFolder(sec,id){const x=(folders[sec]||[]).find(f=>String(f.id)===String(id));if(!x)return;const title=x.name||x.title||'Folder', desc=x.description||x.desc||'';const view=$('#folderView');if(!view)return;view.innerHTML=`<div class="detail-shell"><button class="back-button" id="closeFolder">← ${t('back')}</button><div class="detail-hero"><span>${sec==='trade'?'GLOBAL TRADE':'RESEARCH & KNOWLEDGE'}</span><h1>${esc(title)}</h1><p>${esc(desc)}</p></div><div class="detail-content"><img src="/${img[(Number(id)||0)%img.length]}" alt=""><div><p>${esc(desc)}</p><p>Royal Chilghoza Pine Nuts — Pakistan • Origin • Global.</p></div></div></div>`;view.hidden=false;document.body.classList.add('folder-open');$('#closeFolder').onclick=()=>{view.hidden=true;document.body.classList.remove('folder-open')};view.scrollIntoView({behavior:'smooth',block:'start'})}
async function sendAI(){const input=$('#aiInput'), out=$('#aiResponse');if(!input||!out)return;const q=input.value.trim();if(!q)return;out.textContent='…';try{const d=await api('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,prompt:q,language:lang})});out.textContent=d.answer||d.response||d.message||'Royal AI is ready.'}catch(e){out.textContent=e.message||'AI unavailable.'}}
function addresses(){const a=[['HEADQUARTERS','Main Bazaar, Chilas, Diamer District, Gilgit-Baltistan, Pakistan'],['EXPORT HUB','Silk Road Trade Center, Gilgit, Pakistan'],['PROCESSING YARD','Indus Valley Mineral Yard, Chilas, Pakistan'],['LIAISON OFFICE','Blue Area, Islamabad, Pakistan']];const box=$('#addresses');if(box)box.innerHTML=a.map(x=>`<div class="address-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('')}
function adminUI(){const box=$('#adminPanel');if(!box)return;box.hidden=!admin;if(!admin)return;box.innerHTML=`<div class="admin-head"><div><span class="eyebrow">CONTROL CENTER</span><h2>Website Management</h2></div><button id="adminLogout">${t('logout')}</button></div><div class="admin-grid"><form id="folderForm"><h3>${t('create')}</h3><select id="folderSection"><option value="trade">${t('trade')}</option><option value="research">${t('research')}</option></select><input id="folderName" required placeholder="${t('name')}"><textarea id="folderDesc" placeholder="${t('description')}"></textarea><button>${t('save')}</button></form><div><h3>Existing folders</h3><div id="adminFolders"></div></div></div>`;$('#adminLogout').onclick=()=>{admin=false;adminUI()};$('#folderForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/folders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({section:$('#folderSection').value,name:$('#folderName').value,description:$('#folderDesc').value})});e.target.reset();await loadFolders();adminUI()}catch(err){alert(err.message)}};renderAdminFolders()}
function renderAdminFolders(){const b=$('#adminFolders');if(!b)return;b.innerHTML=['trade','research'].flatMap(sec=>(folders[sec]||[]).map(x=>`<div class="admin-row"><span>${sec}: <b>${esc(x.name||x.title)}</b></span><button data-del="${esc(x.id)}" data-sec="${sec}">${t('delete')}</button></div>`)).join('')||'<p>No folders yet.</p>';$$('[data-del]',b).forEach(btn=>btn.onclick=async()=>{if(!confirm('Delete folder?'))return;try{await api(`/api/folders/${encodeURIComponent(btn.dataset.del)}`,{method:'DELETE'});await loadFolders();adminUI()}catch(e){alert(e.message)}})}
async function login(){const u=prompt('Admin username');if(u===null)return;const p=prompt('Admin password');if(p===null)return;try{await api('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});admin=true;adminUI();alert('Admin login successful.')}catch(e){alert(e.message)}}
function nav(){const menu=$('#languageMenu');$('#languageButton')?.addEventListener('click',e=>{e.stopPropagation();menu.hidden=!menu.hidden});document.addEventListener('click',()=>{if(menu)menu.hidden=true});$$('[data-scroll]').forEach(a=>a.onclick=()=>$(a.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));$('#aiSend')?.addEventListener('click',sendAI);$('#aiInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey))sendAI()});$('#adminLogin')?.addEventListener('click',login);}
languageMenu();addresses();nav();applyLanguage();loadHome();loadFolders();
});
