const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8',...headers}});
const enc=new TextEncoder();
async function digest(text){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(text)))].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function sign(value,secret){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,enc.encode(value));return btoa(String.fromCharCode(...new Uint8Array(sig))).replace(/=+$/,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function sessionCookie(env){const raw=crypto.randomUUID()+'.'+Date.now();const sig=await sign(raw,env.SESSION_SECRET);return `rcpn_session=${raw}.${sig}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=28800`}
async function authed(request,env){const c=request.headers.get('Cookie')||'';const m=c.match(/(?:^|; )rcpn_session=([^;]+)/);if(!m)return false;const [raw,sig]=m[1].split('.');if(!raw||!sig)return false;const ts=Number(raw.split('.')[1]);if(!ts||Date.now()-ts>28800000)return false;return (await sign(raw,env.SESSION_SECRET))===sig}
async function init(env){await env.DB.batch([env.DB.prepare(`CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL, updated_at TEXT NOT NULL);`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS content (id INTEGER PRIMARY KEY AUTOINCREMENT, section TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS media (id INTEGER PRIMARY KEY AUTOINCREMENT, r2_key TEXT NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, caption TEXT NOT NULL, section TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, role TEXT NOT NULL DEFAULT 'editor', created_at TEXT NOT NULL);`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS audit (id INTEGER PRIMARY KEY AUTOINCREMENT, action TEXT NOT NULL, detail TEXT, created_at TEXT NOT NULL);`),env.DB.prepare(`CREATE TABLE IF NOT EXISTS versions (id INTEGER PRIMARY KEY AUTOINCREMENT, content_id INTEGER NOT NULL, snapshot TEXT NOT NULL, created_at TEXT NOT NULL);`)]);}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/')){try{await init(env)}catch(e){return json({error:'D1 not ready. Bind a D1 database before using the admin API.'},503)}
if(url.pathname==='/api/me')return json({auth:await authed(request,env)});
if(url.pathname==='/api/login'&&request.method==='POST'){const {username,password}=await request.json();const expected=env.ADMIN_PASSWORD||'';if(username!=='admin'||!expected||password!==expected)return json({error:'Invalid login.'},401);return json({auth:true,message:'Signed in.'},200,{'Set-Cookie':await sessionCookie(env)});}
if(url.pathname==='/api/settings/theme'){if(request.method==='GET'){const r=await env.DB.prepare(`SELECT value FROM settings WHERE key='theme'`).first();return json({theme:r?JSON.parse(r.value):null})}if(request.method==='PUT'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);const theme=await request.json();await env.DB.prepare(`INSERT INTO settings(key,value,updated_at) VALUES('theme',?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at`).bind(JSON.stringify(theme),new Date().toISOString()).run();await env.DB.prepare(`INSERT INTO audit(action,detail,created_at) VALUES('theme.update',?,?)`).bind(JSON.stringify(theme),new Date().toISOString()).run();return json({ok:true})}}
if(url.pathname==='/api/content'&&request.method==='GET'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);const r=await env.DB.prepare(`SELECT * FROM content ORDER BY id DESC LIMIT 100`).all();return json({items:r.results||[]})}
if(url.pathname==='/api/content'&&request.method==='POST'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);const x=await request.json();await env.DB.prepare(`INSERT INTO content(section,title,description,status,created_at,updated_at) VALUES(?,?,?,?,?,?)`).bind(x.section,x.title,x.description,x.status||'draft',new Date().toISOString(),new Date().toISOString()).run();return json({ok:true})}
if(url.pathname.startsWith('/api/content/')&&request.method==='PATCH'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);const id=Number(url.pathname.split('/').pop());const x=await request.json();await env.DB.prepare(`UPDATE content SET status=?,updated_at=? WHERE id=?`).bind(x.status||'draft',new Date().toISOString(),id).run();return json({ok:true})}
if(url.pathname.startsWith('/api/content/')&&request.method==='DELETE'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);const id=Number(url.pathname.split('/').pop());await env.DB.prepare(`DELETE FROM content WHERE id=?`).bind(id).run();return json({ok:true})}
if(url.pathname==='/api/media'&&request.method==='GET'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);const r=await env.DB.prepare(`SELECT id,r2_key,title,description,caption,section,created_at FROM media ORDER BY id DESC LIMIT 100`).all();const items=(r.results||[]).map(x=>({...x,kind:x.r2_key.match(/\.(mp4|webm|mov)$/i)?'video':x.r2_key.match(/\.pdf$/i)?'pdf':'image'}));return json({items})}
if(url.pathname==='/api/media'&&request.method==='POST'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);const fd=await request.formData();const file=fd.get('file');if(!(file instanceof File))return json({error:'No file'},400);if(file.size>20*1024*1024)return json({error:'File too large (20 MB limit).'},413);const safe=(file.name||'upload').replace(/[^a-zA-Z0-9._-]/g,'_');const key=`media/${Date.now()}-${crypto.randomUUID()}-${safe}`;await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});const now=new Date().toISOString();await env.DB.prepare(`INSERT INTO media(r2_key,title,description,caption,section,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).bind(key,fd.get('title')||safe,fd.get('description')||'',fd.get('caption')||'',fd.get('section')||'research',now,now).run();return json({ok:true,key})}
if(url.pathname.startsWith('/api/media/')&&request.method==='DELETE'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);const id=Number(url.pathname.split('/').pop());const row=await env.DB.prepare(`SELECT r2_key FROM media WHERE id=?`).bind(id).first();if(row)await env.MEDIA.delete(row.r2_key);await env.DB.prepare(`DELETE FROM media WHERE id=?`).bind(id).run();return json({ok:true})}
if(url.pathname.startsWith('/api/media/')&&request.method==='GET'){const key=decodeURIComponent(url.pathname.slice('/api/media/'.length));const obj=await env.MEDIA.get(key);if(!obj)return new Response('Not found',{status:404});const h=new Headers();obj.writeHttpMetadata(h);h.set('etag',obj.httpEtag);return new Response(obj.body,{headers:h})}
if(url.pathname==='/api/ai'&&request.method==='POST'){if(!(await authed(request,env)))return json({error:'Unauthorized'},401);if(!env.AI)return json({error:'Workers AI binding is not configured.'},503);const x=await request.json();const instruction={improve:'Improve grammar and clarity while preserving facts.',summary:'Summarize accurately and briefly.',buyer:'Rewrite for an international buyer while preserving factual claims.',translate:'Translate faithfully; do not invent facts.'}[x.mode]||'Help with the request.';const prompt=`You are Royal AI Assistant for Royal Chilghoza Pine Nuts. Human review is required before publication. ${instruction}\nLanguage: ${x.language}\nText:\n${x.text}`;const out=await env.AI.run('@cf/meta/llama-3.1-8b-instruct',{prompt,max_tokens:800});return json({result:out.response||out})}
return json({error:'Not found'},404)}
const resp=await env.ASSETS.fetch(request);return resp.status===404?env.ASSETS.fetch(new Request(new URL('/index.html',request.url),request)):resp;}}
